-- DATA CLEANING OF INTERNET SALES

SELECT  [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
      --,[PromotionKey]
      --,[CurrencyKey]
      --,[SalesTerritoryKey]
      --,[SalesOrderNumber]
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
     -- ,[OrderQuantity]
      --,[UnitPrice]
      --,[ExtendedAmount]
      --,[UnitPriceDiscountPct]
      --,[DiscountAmount]
      --,[ProductStandardCost]
      ,[TotalProductCost] as [Product Cost]
      ,[SalesAmount]
      --,[TaxAmt]
      --,[Freight]
      --,[CarrierTrackingNumber]
      --,[CustomerPONumber]
      --,[OrderDate]
      --,[DueDate]
      --,[ShipDate]
  FROM [AdventureWorksDW2019].[dbo].[FactInternetSales]
  where left (OrderDateKey, 4) >= 2019;


  -- DATA CLEANING OF PRODUCT TABLE

SELECT p.[ProductKey]
      ,p.[ProductAlternateKey] as [Product ID]
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,p.[EnglishProductName] as [Product Name]
	  ,pc.[EnglishProductCategoryName] as [Product Category]
	  ,sub.[EnglishProductSubcategoryName] as [Sub Category]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      --,[Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      --,[Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      --,[ProductLine]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      --,[ModelName]
      --,[LargePhoto]
      ,p.[EnglishDescription] as [Product Description]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      ,p.[Status]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] as p 
  left join [dbo].DimProductSubcategory as sub on sub.ProductSubcategoryKey = p.ProductSubcategoryKey
  left join [DimProductCategory] as pc on sub.ProductCategoryKey = pc.ProductCategoryKey
  order by p.productkey asc;


  -- DATA CLEANING OF CUSTOMER TABLE

SELECT cus.[CustomerKey]
      ,cus.[GeographyKey]
      ,cus.[CustomerAlternateKey]
      --,[Title]
      ,cus.[FirstName] as [First Name]
      --,[MiddleName]
      ,cus.[LastName] as [Last Name]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      --,[Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,cus.[DateFirstPurchase] as [Purchase Date]
      --,[CommuteDistance]
	  ,geo.[City] as [Customer City]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer] as cus
  left join dbo.DimGeography as geo on geo.GeographyKey = cus.GeographyKey
  order by [CustomerKey] asc;


  -- DATA CLEANING OF CALENDAR TABLE

SELECT [DateKey]
      ,[FullDateAlternateKey]
      --,[DayNumberOfWeek]
      --,[EnglishDayNameOfWeek]
      --,[SpanishDayNameOfWeek]
      --,[FrenchDayNameOfWeek]
      --,[DayNumberOfMonth]
      --,[DayNumberOfYear]
      --,[WeekNumberOfYear]
      ,[EnglishMonthName] as Month, 
	  LEFT([EnglishMonthName], 3) as MonthAbre 
      --,[SpanishMonthName]
      --,[FrenchMonthName]
      ,[MonthNumberOfYear]
      ,[CalendarQuarter] as Quarter
      ,[CalendarYear]
      --,[CalendarSemester]
      --,[FiscalQuarter]
      --,[FiscalYear]
      --,[FiscalSemester]
  FROM [AdventureWorksDW2019].[dbo].[DimDate]
  where CalendarYear >= '2019';